//
// Created by NZP on 2019-4-23.
//

#ifndef NLAI_GRADIENT_BOOSTING_DECISION_TREE_H
#define NLAI_GRADIENT_BOOSTING_DECISION_TREE_H


class GradientBoostingDecisionTree {

};


#endif //NLAI_GRADIENT_BOOSTING_DECISION_TREE_H
